# Generated by Django 4.1.3 on 2022-11-18 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
