# Generated by Django 4.1.3 on 2022-12-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_system", "0002_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="technologies",
        ),
    ]
