# Generated by Django 4.1.3 on 2022-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_project_project_name_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.FileField(upload_to='certifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
