# Generated by Django 4.1.3 on 2022-11-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_managermodel_developermodel_adminmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managermodel',
            name='users',
        ),
    ]
