# Generated by Django 4.1.3 on 2022-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_project_project_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_reporting_manager',
            field=models.CharField(max_length=100, verbose_name='Reporting Manager'),
        ),
    ]
