# Generated by Django 4.1.3 on 2022-11-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_managermodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developermodel',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='developermodel',
            name='users',
        ),
        migrations.AddField(
            model_name='managermodel',
            name='users',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'Developers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminModel',
        ),
        migrations.DeleteModel(
            name='DeveloperModel',
        ),
    ]
