# Generated by Django 4.1.3 on 2022-11-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_designation'),
        ('account', '0004_alter_project_project_reporting_manager'),
    ]

    operations = [
    ]
