# Generated by Django 4.1.3 on 2022-11-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20221121_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
