# Generated by Django 4.1.3 on 2022-11-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_project_project_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_assignee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_bde_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_closing_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_remark',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_reporting_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.CreateModel(
            name='ProjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('project_reporting_manager', models.CharField(max_length=100, verbose_name='Reporting Manager')),
                ('project_bde_manager', models.CharField(max_length=200, verbose_name='BDE Manager')),
                ('project_start_date', models.DateField(verbose_name='Start Date')),
                ('project_closing_date', models.DateField(verbose_name='Closing Date')),
                ('project_remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('project_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Terminated', 'Terminated')], default='Not Started', max_length=50, verbose_name='Status')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='account.project')),
                ('project_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
