# Generated by Django 4.1.3 on 2022-11-23 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_project_project_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectassign',
            old_name='project',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='rating',
            name='developer_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='developer_name'),
        ),
    ]
